In [1]:
a = [
    [1,2,3],
    [4,5,6]
]
a

[[1, 2, 3], [4, 5, 6]]

In [2]:
b = {
    'A' : [1,2,3],
    'B' : [5,6,7]
}
b

{'A': [1, 2, 3], 'B': [5, 6, 7]}

In [3]:
b['A'][1]

2

In [4]:
import numpy as np
x1 = np.arange(10)
x2 = np.arange(4,12)
y1 = np.random.random(10)
y2 = np.random.random(8)
x1,x2,y1,y2

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 4,  5,  6,  7,  8,  9, 10, 11]),
 array([0.3816779 , 0.18507503, 0.31007382, 0.09038493, 0.47236337,
        0.42788587, 0.44741068, 0.25366259, 0.1690731 , 0.41514576]),
 array([0.70893344, 0.90075108, 0.3695051 , 0.11590681, 0.1557851 ,
        0.73578672, 0.75843094, 0.55079943]))

In [5]:
dec = {1: {'name':'kuku','age':22}, 2: {'name':'coco','age':25}}
for name in dec.values():
    if name['age'] > 22:
        print(name['name'])


coco


In [6]:
dec.values()

dict_values([{'name': 'kuku', 'age': 22}, {'name': 'coco', 'age': 25}])

In [7]:
list1 = [num for num in range(100) if num % 5 == 0 if num % 10 == 0]
list1

[0, 10, 20, 30, 40, 50, 60, 70, 80, 90]

In [8]:
set1 = {1,2,3,4,5,6}
set2 = {2,5,3,7,9,8}
set3 = {10,11,22,33,55}
print(set1)
set1.update("gghhhH")
set1.add('Ahmed')
print(set1)
print(set3)

{1, 2, 3, 4, 5, 6}
{1, 2, 3, 4, 5, 6, 'h', 'Ahmed', 'H', 'g'}
{33, 22, 55, 10, 11}


In [9]:
set1.isdisjoint(set2)

False

In [10]:
set1.issuperset(set2)

False

In [11]:
lst = [[1,2,3],
      [4,5,6]]
for i in range(2) :
    for j in range(3):
        print(lst[i][j],end='')
    print()

123
456


In [12]:
x = [[i]*5 for i in range(1,5)]
for i in range(4):
    for j in range(4):
        print(x[i][j],end=' ')
    print( )

1 1 1 1 
2 2 2 2 
3 3 3 3 
4 4 4 4 


In [13]:
c = int(input('Enter col num: '))
r = int(input('Enter row num: '))
x = [[0]*c for i in range(r)]
for i in range(r):
    for j in range(c):
        if i == j:
            x[i][j] = 1
        elif j > i :
            x[i][j] = 0
        elif i < j :
            x[i][j] = 0

for i in range(r):
    for j in range(c):
        print(x[i][j], end=' ')
    print()

Enter col num: 4
Enter row num: 4
1 0 0 0 
0 1 0 0 
0 0 1 0 
0 0 0 1 


In [14]:
c = int(input('Enter col num: '))
r = int(input('Enter row num: '))
x = [[0]*c for i in range(r)]
for i in range(r):
    for j in range(c):
        if (i+j)%2 == 0 :
            x[i][j] = 1

for i in range(r):
    for j in range(c):
        print(x[i][j], end=' ')
    print()

Enter col num: 4
Enter row num: 4
1 0 1 0 
0 1 0 1 
1 0 1 0 
0 1 0 1 
