In [9]:
from random import *

In [18]:
import random

def scramble(word):
    if len(word) > 3:
        middle = list(word[1:-1])
        random.shuffle(middle)
        return word[0] + ''.join(middle) + word[-1]
    else:
        return word

text = input("Enter a text: ").split()
scrambled_text = [scramble(word) for word in text]
print(' '.join(scrambled_text))


Enter a text: muaeen
maeeun


In [22]:
def roman_to_int(s):
    roman_val = {'I': 1, 'V': 5, 'X': 10, 'L': 50, 'C': 100, 'D': 500, 'M': 1000}
    int_val = 0
    for i in range(len(s)):
        if i > 0 and roman_val[s[i]] > roman_val[s[i - 1]]:
            int_val += roman_val[s[i]] - 2 * roman_val[s[i - 1]]
        else:
            int_val += roman_val[s[i]]
    return int_val

roman_numeral = input("Enter a Roman numeral: ")
print(roman_to_int(roman_numeral))


Enter a Roman numeral: I
1


In [23]:
m = 'mua9876 1' 
found = False
position = 0
while not found and position < len(m) :
    if m[position].isdigit() :
        found = True
    else :
        position = position + 1
if found :
    print("First digit occurs at position", position)
else :
    print("The string does not contain a digit.")

First digit occurs at position 3


In [ ]:
(XXX)XXX-XXXX)

In [1]:
Number = input('Enter your number :')
position = 0 
valid = len(Number) == 13
while valid and position < len(Number):
    if position == 0:
        valid = Number[position] == '('
    elif position == 4:
        valid = Number[position] == ')'
    elif position == 8:
        valid = Number[position] == '-'
    else :
        valid = Number[position].isdigit()
    position = position + 1
if valid :
    print(f'right {Number}')
else :
    print('Wrong')

Enter your number :(123)123-1234
right(123)123-1234


+(968)92945402

In [2]:
OmanNumber = input('Enter your number :')
position = 0 
valid = len(OmanNumber) == 14
while valid and position < len(OmanNumber):
    if position == 0:
        valid = OmanNumber[position] == '+'
    elif position == 1:
        valid = OmanNumber[position] == '('
    elif position == 5 :
        valid = OmanNumber[position] == ')'
    else :
        valid = OmanNumber[position].isdigit()
    position = position + 1
if valid :
    print(f'its right {OmanNumber}')
else :
    print('Wrong Number')

Enter your number :+(968)92945402
its right +(968)92945402


In [ ]:
Pass = input('Enter your passowrd')
position = 0 
valid = len(Pass) >= 8
while valid and position >= 8:
    if valid 

In [25]:
P = input('Enter yous pass :')
upper = 0
lower = 0
number = 0
sy = 0
valid = len(P) >= 8
if valid :
    for i in range(len(P)) :
        if P[i].isupper() :
            upper +=1
        elif P[i].islower() :
            lower +=1
        elif P[i].isdigit() :
            number +=1
        else :
            sy += 1

if (upper > 0 and lower > 0 and number > 0 and sy > 0) :
    print(f'its right {P}')
else :
    print('Wrong Number')

Enter yous pass :Muaeen@1998
its right Muaeen@1998


In [60]:
txt = "345-567"

st = txt.strip("-")
x = "".join(st)

print(x)

345-567


In [13]:
txt = "345-567"

parts = txt.split("-")
x = "".join(parts)  

print(x)  

345567


In [37]:
txt = ",,,,,rrttgg.....banana....rrr"

x = txt.strip(",.grt")

print(x)

banana


In [116]:
random()

0.5837538288936345

In [117]:
round(random()*100)

20

In [115]:
randrange(100)

23

In [1]:
from random import *
random_number = randrange(100)
done = False
while not done :
    Q = int(input('Enter Number :'))
    if (Q < 0) or (Q > 100 ):
        print('Outside range')
    else :
        if Q == random_number :
            done = True
            print('Grate')
        elif Q < random_number :
            print('Go up')
        elif Q > random_number :
            print('Go down')

Enter Number :10
Go up
Enter Number :20
Go up
Enter Number :30
Go up
Enter Number :40
Go up
Enter Number :50
Go down
Enter Number :45
Grate


In [11]:
x = range(10)
for i in x :
    print(i)
    if i == 5 :
        print('we skip', i)
        continue
    if i > 5 and i <9:
        break

0
1
2
3
4
5
we skip 5
6


In [16]:
balance = 10000   
def withdraw(amount) :
    global balance
    if balance >= amount :
        balance = balance - amount
    print('balance = ', balance)

In [17]:
withdraw(350)

balance =  9650


In [20]:
def main():
    x = 3
    y = 4
    falseSwap(x,y)
    print(x,y)
def falseSwap(a,b):
    temp = a
    a = b
    b = temp
print(falseSwap(5,8))

None


In [24]:
#wrong
a = '159'
def sum_digits(a):
    for i in a[:]:
        i = int(i)
        x =+ i + 10
    print(x)
sum_digits(a)

19


In [18]:
1+2+9

12

In [7]:
a = '234'
def sum_digits(a):
    a = int(a)
    for i in range(a):
        #i = int(i)
        x = i + i
    print(x)
sum_digits(a)

466


In [24]:
m = '12345'
def sum_string_digits(s):
    if s.isdigit():
        return sum(int(digit) for digit in s)
    else:
        return "Input string is not numeric"

sum_string_digits('123')


6

In [25]:
a = 1,2,3,4
range(a)

TypeError: 'tuple' object cannot be interpreted as an integer

In [23]:
from math import *
def area(n,side):
    area = (n*pow(side,2))/(4*tan(pi/n))
    return area

In [24]:
area(5,6.5)

72.69017017488385

In [32]:
def countVowels(string):
    count = 0
    vowels = "aeiouAEIOU"
    for i in string:
        if i in vowels:
            count += 1
    return count
Name = 'Muaeen Gharib Ali'
countVowels(Name)

8

In [38]:
x = [1,2,3,4,5]
print(x[2])
x[2] = 9
x

3


[1, 2, 9, 4, 5]

In [39]:
primes = [2, 3, 5, 7, 11]
primes

[2, 3, 5, 7, 11]

In [5]:
listA = [22,3,-2,-1,10,1]
ne = 0
product = 1
for i in listA :
    print(i)
    product = product * i
    if i < 0 :
        ne += 1
print('_______\n',sum(listA))
print('_______\n',ne)
print('_______\n',product)

22
3
-2
-1
10
1
_______
 33
_______
 2
_______
 1320


In [19]:
listB = [1,2,3]
sum(listB)

6

In [20]:
del listB[0]

In [21]:
listB

[2, 3]

In [8]:
import pandas as pd
data = {'A':[1,2,3],
     'B':[2,3,4]}
df = pd.DataFrame(data)
df

A  B
0  1  2
1  2  3
2  3  4

In [35]:
listC = [3,'a',4,'b',6,8,0]
listC[-3:-1]

[6, 8]

In [9]:
df.sort_values(ascending=)

A    6
B    9
dtype: int64

KeyError: 0

In [26]:
x = [1,2,3]
x.extend([[4,5]])
z = '|'.join(x)
z

TypeError: sequence item 0: expected str instance, int found

In [10]:
y=[1,2,3]
y = '|'.join(map(str,y))
print(y)
print(type(y))

1|2|3
<class 'str'>


In [12]:
r = [i for i in range(5) if (i % 2==0)]
r


[0, 2, 4]

In [28]:
def multiply(values, factor):
    for i in range(len(values)):
        values[i] = values[i] * factor
    print()

In [29]:
v = [1,2,3,4]
f = 2
multiply(v,f)

In [25]:
inp = [1,3,5,0,4,3]
counts = i for i in range(1,7)
for x in inp :
    if x in counts :
        counts[x] +=1
    for x in counts.items():
        print(f'{x}: {counts}', end=' ')

SyntaxError: invalid syntax (2860377109.py, line 2)

In [39]:
def roll_sum(a) :
    counts = {i:0 for i in range(1,7)}
    for x in a :
        if x in counts :
            counts[x] += 1
            for x,count in counts.items():
                print(f'{x}: {count},',end=' ')
a = [1,3,5,0,4,3]
roll_sum(a)

1: 1, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 1: 1, 2: 0, 3: 1, 4: 0, 5: 0, 6: 0, 1: 1, 2: 0, 3: 1, 4: 0, 5: 1, 6: 0, 1: 1, 2: 0, 3: 1, 4: 1, 5: 1, 6: 0, 1: 1, 2: 0, 3: 2, 4: 1, 5: 1, 6: 0, 

In [40]:
a = [
    [1,2,3],
    [4,5,6]
]
a

[[1, 2, 3], [4, 5, 6]]

In [47]:
b = {
    'A' : [1,2,3],
    'B' : [5,6,7]
}
b

{'A': [1, 2, 3], 'B': [5, 6, 7]}

In [51]:
b['A'][1]

2

In [1]:
import numpy as np
x1 = np.arange(10)
x2 = np.arange(4,12)
y1 = np.random.random(10)
y2 = np.random.random(8)
x1,x2,y1,y2

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 4,  5,  6,  7,  8,  9, 10, 11]),
 array([0.1643263 , 0.66456553, 0.84294607, 0.77930444, 0.71105369,
        0.53163007, 0.8621718 , 0.01609003, 0.96887739, 0.17466951]),
 array([0.10307356, 0.7930381 , 0.56234339, 0.43068561, 0.37119043,
        0.7999139 , 0.47050556, 0.26879035]))

In [4]:
import pandas as pd
df1 = pd.DataFrame({'x' : x1,
                  'y' : y1})
df1

x         y
0  0  0.164326
1  1  0.664566
2  2  0.842946
3  3  0.779304
4  4  0.711054
5  5  0.531630
6  6  0.862172
7  7  0.016090
8  8  0.968877
9  9  0.174670

In [3]:
df2 = pd.DataFrame(
    {
        'x': x2,
        'y': y2
    }

)
df2

x         y
0   4  0.312861
1   5  0.837248
2   6  0.413209
3   7  0.764857
4   8  0.867231
5   9  0.665115
6  10  0.171979
7  11  0.971239

In [4]:
df1 = df1.merge(df2,how='outer')
df1

x         y
0    0  0.993076
1    1  0.955492
2    2  0.489750
3    3  0.717730
4    4  0.542569
5    5  0.487651
6    6  0.475917
7    7  0.256408
8    8  0.488675
9    9  0.882096
10   4  0.312861
11   5  0.837248
12   6  0.413209
13   7  0.764857
14   8  0.867231
15   9  0.665115
16  10  0.171979
17  11  0.971239

In [5]:
df1

x         y
0    0  0.993076
1    1  0.955492
2    2  0.489750
3    3  0.717730
4    4  0.542569
5    5  0.487651
6    6  0.475917
7    7  0.256408
8    8  0.488675
9    9  0.882096
10   4  0.312861
11   5  0.837248
12   6  0.413209
13   7  0.764857
14   8  0.867231
15   9  0.665115
16  10  0.171979
17  11  0.971239

In [2]:
a = {'A':
    {
        'a':[1,2],
        'b' :[8,6]
    },
     'B':{
         'a':[9,65],
         'b' :[34,66]
     }
}

In [3]:
a

{'A': {'a': [1, 2], 'b': [8, 6]}, 'B': {'a': [9, 65], 'b': [34, 66]}}

In [6]:
d = pd.DataFrame(a)
d

A         B
a  [1, 2]   [9, 65]
b  [8, 6]  [34, 66]

In [7]:
for i,x in d:
    if x>20:
        print('')

ValueError: not enough values to unpack (expected 2, got 1)

In [1]:
dec = {1: {'name':'kuku','age':22}, 2: {'name':'coco','age':25}}
for name in dec.values():
    if name['age'] > 22:
        print(name['name'])


coco


In [3]:
dec.values()

dict_values([{'name': 'kuku', 'age': 22}, {'name': 'coco', 'age': 25}])

In [16]:
list1 = [num for num in range(100) if num % 5 == 0 if num % 10 == 0]
list1

[0, 10, 20, 30, 40, 50, 60, 70, 80, 90]

In [34]:
set1 = {1,2,3,4,5,6}
set2 = {2,5,3,7,9,8}
set3 = {10,11,22,33,55}
print(set1)
set1.update("gghhhH")
set1.add('Ahmed')
print(set1)
print(set3)

{1, 2, 3, 4, 5, 6}
{1, 2, 3, 4, 5, 6, 'Ahmed', 'h', 'H', 'g'}
{33, 22, 55, 10, 11}


In [21]:
set1.isdisjoint(set2)

False

In [24]:
set1.issuperset(set2)

False

In [26]:
set1.issubset(set3)

False

In [ ]:
set1.

In [53]:
lst = [[1,2,3],
      [4,5,6]]
for i in range(2) :
    for j in range(3):
        print(lst[i][j],end='')
    print()

123
456


In [101]:
x = [[i]*5 for i in range(1,5)]
for i in range(4):
    for j in range(4):
        print(x[i][j],end=' ')
    print( )

4 4 4 4 
1 1 1 1 
2 2 2 2 
3 3 3 3 


In [155]:
c = int(input('Enter col num: '))
r = int(input('Enter row num: '))
x = [[0]*c for i in range(r)]
for i in range(r):
    for j in range(c):
        if i == j:
            x[i][j] = 1
        elif j > i :
            x[i][j] = 0
        elif i < j :
            x[i][j] = 0

for i in range(r):
    for j in range(c):
        print(x[i][j], end=' ')
    print()

Enter col num: 4
Enter row num: 4
1 0 0 0 
0 1 0 0 
0 0 1 0 
0 0 0 1 


In [156]:
c = int(input('Enter col num: '))
r = int(input('Enter row num: '))
x = [[0]*c for i in range(r)]
for i in range(r):
    for j in range(c):
        if (i+j)%2 == 0 :
            x[i][j] = 1

for i in range(r):
    for j in range(c):
        print(x[i][j], end=' ')
    print()

Enter col num: 4
Enter row num: 4
1 0 1 0 
0 1 0 1 
1 0 1 0 
0 1 0 1 


In [211]:
dict = {}
with open("new.txt", "r") as file_:
    for ln in file_:
        (key, val) = ln.split()
        dict[key] = float(val)  

print(dict)
max_ = max(dict,key=dict.get)
print(max_)
ave = (sum(dict.values())/len(dict.values()))
ave

{'Khalid': 995.0, 'Salim': 876.0, 'Issa': 877.0}
Khalid


916.0

In [212]:
max_ = max(dict,key=dict.get)
print(max_)
ave = (sum(dict.values())/len(dict.values()))
ave

Khalid


916.0

In [8]:
file_ = open('new.txt')
data = []
for line in file_ :
    line = line.strip()
    item = line.split(':')
    data.append(item)
sal = 0 
maxsal = []
for i in data :
    if float(i[1]) > sal:
        maxsal = i
    sal = float(i[1])
print(maxsal[0],maxsal[1])
file_.close()



Issa 877
